[package]
name = "raven"
version = "1.1.0"
edition = "2021"
authors = ["martian56"]
description = "A modern programming language with advanced features"
license = "MIT"
repository = "https://github.com/martian56/raven"
homepage = "https://github.com/martian56/raven"
keywords = ["programming", "language", "compiler", "interpreter"]
categories = ["development-tools", "command-line-utilities"]

[dependencies]
clap = "4.1"

[profile.release]
opt-level = 1
lto = true
codegen-units = 1

